### ISSUE TITLE
ActionMenu: When 0 options set, an empty div is displayed

### ISSUE THREAD

**Issue by datio** [svar-widgets/menu#1]
Ideally, it wouldn't open at all when no options exist.

**Comment by datio** [comment]
Fixed by using:

```svelte
<ActionMenu
    {options}
    at="point"
    onclick={handleMenuClick}
    css={!options.length ? 'hidden' : ''}
>
```

and 

```css
<style>
	:global(.wx-menu.hidden) {
		display: none !important;
	}

	:global(.wx-menu.hidden .wx-item) {
		display: none !important;
	}
</style>
```
